<a href="https://colab.research.google.com/github/ngish-012/Hello-world/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY CALCULATIONS


In [11]:
#Calculating apple yields of different areas using temp, humidity and rainfall data

In [12]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [13]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]


In [14]:
weights = [w1, w2, w3]

In [15]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

In [16]:
crop_yield(kanto,weights)

56.8

In [17]:
!pip install numpy
import numpy as np


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [18]:
kanto = np.array([73, 67, 43])
kanto


array([73, 67, 43])

In [19]:
#Numpy arrays have the type ndarray.
type(kanto)

numpy.ndarray

In [20]:
#Just like lists, Numpy arrays support the indexing notation [].
weights[0]
kanto[2]

43

In [21]:
#We can now compute the dot product of the two vectors using the np.dot function.
np.dot(kanto, weights)

56.8

In [22]:
kanto


array([73, 67, 43])

In [23]:
weights


[0.3, 0.2, 0.5]

In [24]:
kanto*weights

array([21.9, 13.4, 21.5])

In [25]:
#We can achieve the same result with low-level operations supported by Numpy arrays: 
# performing an element-wise multiplication and calculating the resulting numbers' sum
(kanto*weights).sum()

56.8

In [26]:
#The * operator performs an element-wise multiplication of two arrays if they have the same size.
# The sum method calculates the sum of numbers in an array.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr1 * arr2

array([ 4, 10, 18])

In [27]:
arr2.sum()

15

In [28]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)


In [29]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

CPU times: user 201 ms, sys: 0 ns, total: 201 ms
Wall time: 202 ms


833332333333500000

In [30]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: user 2.14 ms, sys: 5 µs, total: 2.15 ms
Wall time: 2.16 ms


833332333333500000

In [31]:
#We can now go one step further and represent the climate data for all the regions using a single 2-dimensional Numpy array.
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [32]:
# 2D array (matrix)
climate_data.shape

(5, 3)

In [33]:
weights = np.array([0.3, 0.2, 0.5])

In [34]:
weights2=np.array(weights)
weights2.shape

(3,)

In [35]:
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])
arr3.shape

(2, 2, 3)

In [36]:
#All the elements in a numpy array have the same data type. You can check the data type of an array using the .dtype property.
climate_data.dtype

dtype('int64')

In [37]:
weights

array([0.3, 0.2, 0.5])

In [38]:
#We can use the np.matmul function or the @ operator to perform matrix multiplication
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [39]:
climate_data@weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [40]:
#WORKING WITH CSV DATA FILES
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7f7e5fd32650>)

In [42]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [43]:
climate_data.shape

(10000, 3)

In [47]:
weights = np.array([0.3, 0.2, 0.5])
yields = climate_data @ weights
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [48]:
yields.shape

(10000,)

In [50]:
#Adding the yields column to the climate data using np.concatenate
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis = 1)
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [52]:
#Let's write the final results from our computation above back to a file using the np.savetxt function.
np.savetxt('climate_results.txt', 
           climate_results, 
           fmt='%.2f', 
           delimiter=',',
           header='temperature,rainfall,humidity,yeild_apples', 
           comments='')
urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7f7e5fd35950>)

In [53]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])